import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="min-h-screen bg-black">
      <Head>
        <title>Space Posters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/solar-system.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins&display=swap')
        </style>
      </Head>
      <div class="font-Poppins">
        <Header />
        <Hero />
        <Footer />
      </div>
    </div>
  );
}
